workspace:
  base: /go/src
  path: github.com/appleboy/gin-jwt

pipeline:
  build:
    image: appleboy/golang-testing:${GO_VERSION}
    commands:
      - make embedmd-check
      - make vet
      - make lint
      - make fmt-check
      - coverage all

  codecov:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
    files:
      - .cover/coverage.txt
    when:
      event: [ push, pull_request ]

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ success, failure ]

matrix:
  GO_VERSION:
    - 1.8.4
    - 1.9.1
