kind: pipeline
name: lint

clone:
  depth: 50

steps:
- name: testing
  image: golang:1.11
  pull: true
  environment:
    GO111MODULE: on
  commands:
  - make vet
  - make revive
  - make embedmd-check
  - make fmt-check
  - make misspell-check

trigger:
  event:
  - push
  - pull_request

---
kind: pipeline
name: testing

workspace:
  base: /go
  path: src/github.com/appleboy/gin-jwt

clone:
  depth: 50

steps:
- name: testing
  image: golang:1.11
  pull: true
  environment:
    GO111MODULE: on
  commands:
  - make test
  - make coverage

- name: codecov
  image: robertstettner/drone-codecov
  settings:
    token:
      from_secret: codecov_token

trigger:
  event:
  - push

---
kind: pipeline
name: notification

clone:
  disable: true

steps:
- name: discord
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
  when:
  status:
  - success
  - failure

depends_on:
- testing
- lint
